AWSTemplateFormatVersion: 2010-09-09
Description: Creates subnet in Default vpc

Parameters:
  VPCID:
    Description: Enter VPC ID to place the subnet in
    Type: String

Resources:
  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCID
      CidrBlock: 172.31.48.0/20
      AvailabilityZone: "ap-south-1a"
  myRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCID
  mySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref mySubnet
      RouteTableId: !Ref myRouteTable

